---
title: HMS Science Olympiad
timezone: UTC
collections:
  config:
    title: Config
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: scioly-website@metoki.anonaddy.me
baseurl: 
url: https://hmsscioly.js.org
markdown: kramdown
github:
  repo: HMSSO/SciOly-Website
  branch: main
include:
- _redirects
