---
title: HMS Science Olympiad
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hmsscienceolympiad@hudson.k12.oh.us
baseurl: 
url: https://hmsscioly.js.org
markdown: kramdown
github:
  repo: HMSSO/SciOly-Website
  branch: main
include:
- _redirects
